"""updated user model

Revision ID: 0aa089892da6
Revises: f55161bb36ac
Create Date: 2025-05-18 20:16:04.994696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0aa089892da6'
down_revision = 'f55161bb36ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('date_birth', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.Enum('PUBLIC', 'FRIENDS', 'PRIVATE', name='visibilityenum'), nullable=False))
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=255), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.create_unique_constraint(None, ['fs_uniquifier'])
        batch_op.create_unique_constraint(None, ['phone'])
        batch_op.drop_column('email_confirmed_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('fs_uniquifier')
        batch_op.drop_column('gender')
        batch_op.drop_column('date_birth')
        batch_op.drop_column('phone')
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    op.drop_table('roles_users')
    op.drop_table('role')
    # ### end Alembic commands ###
