"""Add visibility to Post

Revision ID: 464d45ed9fa5
Revises: 4251d8d92865
Create Date: 2025-04-15 22:32:20.940701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464d45ed9fa5'
down_revision = '4251d8d92865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'FRIENDS', 'PRIVATE', name='visibilityenum'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
