"""Add friendships table and friend_ids helper

Revision ID: 49281d1858b6
Revises: 464d45ed9fa5
Create Date: 2025-04-29 16:51:06.649378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49281d1858b6'
down_revision = '464d45ed9fa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friendships')
    # ### end Alembic commands ###
