"""added timestamp to likes

Revision ID: 5bf642e554ca
Revises: ab9bfab7d17e
Create Date: 2025-05-24 18:32:37.262511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf642e554ca'
down_revision = 'ab9bfab7d17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('like', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
