"""posts relationship fix

Revision ID: cfbb70c19d42
Revises: 80eda369586c
Create Date: 2025-05-21 00:46:19.204020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfbb70c19d42'
down_revision = '80eda369586c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_joined',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('date_joined',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
